spring:
  application:
    name: comunicacao-api
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/comunicacao_db
    driverClassName: org.postgresql.Driver
    username: comunicacao
    password: comunicacao
    hikari:
      maximum-pool-size: 2
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    contexts: dev
    parameters:
      schema: comunicacao

server:
  port: 8080